name: Build SunamoVcf

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build SunamoVcf
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoVcf/SunamoVcf.csproj

    - name: Build
      run: dotnet build SunamoVcf/SunamoVcf.csproj --configuration Release --no-restore

  test:
    name: Test SunamoVcf.Tests
    runs-on: ${{ matrix.os }}
    needs: build

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoVcf.Tests/SunamoVcf.Tests.csproj

    - name: Build tests
      run: dotnet build SunamoVcf.Tests/SunamoVcf.Tests.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test SunamoVcf.Tests/SunamoVcf.Tests.csproj --configuration Release --no-build --verbosity normal
      continue-on-error: true
